<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFs58ypn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFs58ypn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFs58ypn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFs58ypn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFs58ypn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fs58ypn',
    'container.build_id' => '247c5454',
    'container.build_time' => 1618837554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFs58ypn');
